[general]
timezone = "Asia/Seoul"
output_dir = "output"
report_filename = "daily_report.html"
chart_dir = "charts"
lookback_days = 200

[email]
from_name = "AutoStock Bot"
from_addr = "bamlong0405@gmail.com"
to_addrs = ["bamlong0405@gmail.com"]
subject = "[AutoStock] Daily Signals"

[universe]
krx_mode = "ALL"              # "ALL" -> KOSPI+KOSDAQ 전체 자동 로드, "LIST" -> 아래 krx 리스트 사용
krx = []                      # krx_mode="LIST"일 때만 사용
yahoo = []                    # 해외 심볼

exclude_etf_etn_spac = true   # 이름 기반 간단 제외
max_symbols = 0               # 0=무제한 (테스트시에는 50~200 권장)
name_filters_exclude = ["ETF","ETN","스팩","SPAC"]
