# =========================
# AutoStock Config (KST)
# =========================

[general]
timezone        = "Asia/Seoul"
output_dir      = "output"
report_filename = "daily_report.html"
chart_dir       = "charts"
lookback_days   = 200          # 분석용 데이터 기간(영업일 기준 아님)

[email]
from_name = "AutoStock Bot"
from_addr = "bamlong0405@gmail.com"      # 발신 Gmail 주소
to_addrs  = ["bamlong0405@gmail.com"]    # 수신자(복수 가능)
subject   = "[AutoStock] Daily Signals"

[email_options]
email_only_signals       = true     # 메일엔 BUY/SELL만
include_charts           = false    # 메일 차트 제외(용량 보호)
max_email_charts         = 0
max_email_rows           = 300
include_hold_in_report   = true     # 저장되는 daily_report.html에는 HOLD 포함
attach_buy_report        = true
max_buy_charts           = 30
# 첨부 리포트용 옵션(뉴스/공시)
max_news_per_symbol      = 3
max_filings_per_symbol   = 3

[universe]
# 코스피+코스닥 전체(초기엔 limit로 속도 조절 권장)
krx_mode = "ALL"                  # LIST | ALL
krx = []                          # LIST 일 때만 사용
yahoo = []                        # 해외 종목 사용 시 추가
exclude_etf_etn_spac = true       # ETF/ETN/스팩 제외
max_symbols = 0                   # 0=제한 없음 (점검 시 200 같은 값 권장)
name_filters_exclude = ["ETF","ETN","스팩","SPAC"]

# =========================
# 전략 모드 선택/레짐
# =========================
[mode]
signal_mode = "default"              # "default" | "blog"

# 레짐(시장 국면) 오버레이
regime_symbol = "069500"             # KODEX200
regime_ma_days = 200
regime_disable_buy_in_bear = false   # ← 초기 진단 위해 OFF (시장 좋아지면 true로)

# -------------------------
# 블로그 전략 파라미터
# -------------------------
[blog_signals]
rsi_period           = 14
divergence_lookback  = 30
div_half_window      = 20
macd_fast   = 12
macd_slow   = 26
macd_signal = 9
require_bullish_engulfing = false
require_volume_surge      = false
volume_surge_multiplier   = 1.5

# -------------------------
# 기본(기존) 전략 파라미터
# -------------------------
[signals]
williams_r_period = 14
williams_r_buy  = -75   # -85 -> 완화
williams_r_sell = -20

rsi_period = 14
rsi_buy  = 40           # 35 -> 완화
rsi_sell = 70

obv_trend_lookback = 10
obv_slope_min = -0.0001

ma_short = 5
ma_mid   = 20
ma_long  = 60

use_bullish_candle = false
use_bearish_candle = false
require_above_ma20_for_buy = false
require_below_ma20_for_sell = false

buy_score_threshold  = 2
sell_score_threshold = 2

# =========================
# 백테스트(옵션)
# =========================
[backtest]
enabled = false
lookback_days = 900
market_filter_symbol = "069500"
market_ma_days = 200
liquidity_lookback = 20
liquidity_min_avg_value = 500000000
max_hold_days = 20
atr_period = 14
stop_atr_mult = 0.0
trail_atr_mult = 0.0
cost_bps_per_side = 25
summary_top_n = 50

# =========================
# 필터/혼잡제어/보조
# =========================
[filters]
# 회전율 필터(시총 대비 거래대금 %) — 초기엔 OFF로 진단, 안정화 후 true로 변경
use_turnover = false
turnover_min_pct_kospi  = 0.15     # 0.15% (예시)
turnover_min_pct_kosdaq = 0.25     # 0.25% (예시)

[overcrowd]
enabled  = true
max_buys = 120
rank_metric = "turnover_pct"       # "turnover_pct" | "obv_slope" | "ma20_gap"

[bbands]            # 볼린저밴드: 리포트 참고용
enabled = true
period  = 20
stdev   = 2.0
