[general]
timezone = "Asia/Seoul"
output_dir = "output"
report_filename = "daily_report.html"
chart_dir = "charts"
lookback_days = 200

[email]
from_name = "AutoStock Bot"
from_addr = "bamlong0405@gmail.com"
to_addrs = ["bamlong0405@gmail.com"]
subject = "[AutoStock] Daily Signals"

[universe]
krx_mode = "ALL"              # "ALL" -> KOSPI+KOSDAQ 전체 자동 로드, "LIST" -> 아래 krx 리스트 사용
krx = []                      # krx_mode="LIST"일 때만 사용
yahoo = []                    # 해외 심볼

exclude_etf_etn_spac = true   # 이름 기반 간단 제외
max_symbols = 0               # 0=무제한 (테스트시에는 50~200 권장)
name_filters_exclude = ["ETF","ETN","스팩","SPAC"]

[signals]
williams_r_period = 14
williams_r_buy  = -80
williams_r_sell = -20
rsi_period = 14
rsi_buy  = 30
rsi_sell = 70
obv_trend_lookback = 10
obv_slope_min = 0.0
ma_short = 5
ma_mid   = 20
ma_long  = 60
use_bearish_candle = true
use_bullish_candle = true
require_above_ma20_for_buy = true
require_below_ma20_for_sell = true

[backtest]
enabled = false
lookback_days = 900
market_filter_symbol = "069500"
market_ma_days = 200
liquidity_lookback = 20
liquidity_min_avg_value = 500000000
max_hold_days = 20
atr_period = 14
stop_atr_mult = 0.0
trail_atr_mult = 0.0
cost_bps_per_side = 25
summary_top_n = 50

[email_options]
email_only_signals = true      # 메일엔 BUY/SELL만
include_charts      = false    # ✅ 메일 본문 차트 제외
max_email_charts    = 0        # 차트 0개(보내지 않음)
max_email_rows      = 300      # ✅ 메일 표 최대 행수 (필요시 200~500 사이 권장)
include_hold_in_report = true  # 로컬/아티팩트 보고서는 HOLD 포함
split_emails        = false    # (옵션) 여러 통으로 쪼개 전송할지
