[general]
timezone = "Asia/Seoul"
output_dir = "output"
report_filename = "daily_report.html"
chart_dir = "charts"
lookback_days = 200

[email]
from_name = "AutoStock Bot"
from_addr = "bamlong0405@gmail.com"
to_addrs = ["bamlong0405@gmail.com"]
subject = "[AutoStock] Daily Signals"

[universe]
krx_mode = "ALL"              # "ALL" -> KOSPI+KOSDAQ 전체 자동 로드, "LIST" -> 아래 krx 리스트 사용
krx = []                      # krx_mode="LIST"일 때만 사용
yahoo = []                    # 해외 심볼

exclude_etf_etn_spac = true   # 이름 기반 간단 제외
max_symbols = 0               # 0=무제한 (테스트시에는 50~200 권장)
name_filters_exclude = ["ETF","ETN","스팩","SPAC"]

[signals]
# Williams %R
williams_r_period = 14
williams_r_buy  = -80
williams_r_sell = -20

# RSI
rsi_period = 14
rsi_buy  = 30
rsi_sell = 70

# OBV 추세 체크
obv_trend_lookback = 10
obv_slope_min = 0.0

# 이동평균
ma_short = 5
ma_mid   = 20
ma_long  = 60

# 캔들/MA 조건
use_bearish_candle = true
use_bullish_candle = true
require_above_ma20_for_buy = true
require_below_ma20_for_sell = true

[email_options]
email_only_signals = true      # 메일에는 BUY/SELL만 포함
max_email_charts   = 80        # 메일에 포함할 차트 최대 개수(과대용량 방지)
include_hold_in_report = true  # 로컬 HTML 리포트엔 HOLD도 포함(원하면 false로)
